### ISSUE TITLE
use luasocket i get error

### ISSUE THREAD

**Issue by lijieaa** [aarzilli/golua#100]
runtime: unknown pc 0x1010401
stack: frame={sp:0x1d0dfed80, fp:0x0} stack=[0x0,0x1d0dff810)
00000001d0dfec80:  00000131edba93b0  000000000101a8a8 
00000001d0dfec90:  00000131e83b4300  00000001d0dfecb8 
00000001d0dfeca0:  00000001d0dfed08  0000000000000000 
00000001d0dfecb0:  0000000000000002  00000131edbd5a79 
00000001d0dfecc0:  00000001d0dfecd8  0000000000000001 
00000001d0dfecd0:  00000131e83b4300  726f6e3a656c7974 
00000001d0dfece0:  746e6f663b6c616d  3a7468676965772d 
00000001d0dfecf0:  6f6c6f633b303034  623b666666233a72 
00000001d0dfed00:  6e756f72676b6361  3a726f6c6f632d64 
00000001d0dfed10:  3b66663939623223  3a79616c70736964 
00000001d0dfed20:  743b656e696c6e69  67696c612d747865 
00000001d0dfed30:  7265746e65633a6e  0000000000000064 
00000001d0dfed40:  00000131e83b4458  0000000066d8f24d 
00000001d0dfed50:  7035207870323a67  6772616d3b302078 
00000001d0dfed60:  3a7466656c2d6e69  7265766f3b787038 
00000001d0dfed70:  6469683a776f6c66  00000000010103e7 
00000001d0dfed80: <757364622e206775  0000000066d8d2f0 
00000001d0dfed90:  726f6c6f637b7463  6f663b303030233a 
00000001d0dfeda0:  3a657a69732d746e  00000131e83b4300 
00000001d0dfedb0:  000000006d08bb79  00000131e83b4458 
00000001d0dfedc0:  000000006d08bb79  0000000000000260 
00000001d0dfedd0:  00000131edbdad80  00000131edba9480 
00000001d0dfede0:  0000000000000006  0000000066d8213c 
00000001d0dfedf0:  657269642d63702d  707b7069742d7463 
00000001d0dfee00:  3a6e6f697469736f  0000000066d81a3d 
00000001d0dfee10:  00000131edba5630  622e207400000004 
00000001d0dfee20:  00000131edbd5578  00000131e83b4300 
00000001d0dfee30:  00000131edba94f0  00000131edba94d0 
00000001d0dfee40:  00000131edba94c0  0000000000000240 
00000001d0dfee50:  00000131edbd4940  00000131edba94a0 
00000001d0dfee60:  0000000000000002  00000000010101c1 
00000001d0dfee70:  00000131e83b4300  00000000010107eb 
runtime: unknown pc 0x1010401
stack: frame={sp:0x1d0dfed80, fp:0x0} stack=[0x0,0x1d0dff810)
00000001d0dfec80:  00000131edba93b0  000000000101a8a8 
00000001d0dfec90:  00000131e83b4300  00000001d0dfecb8 
00000001d0dfeca0:  00000001d0dfed08  0000000000000000 
00000001d0dfecb0:  0000000000000002  00000131edbd5a79 
00000001d0dfecc0:  00000001d0dfecd8  0000000000000001 
00000001d0dfecd0:  00000131e83b4300  726f6e3a656c7974 
00000001d0dfece0:  746e6f663b6c616d  3a7468676965772d 
00000001d0dfecf0:  6f6c6f633b303034  623b666666233a72 
00000001d0dfed00:  6e756f72676b6361  3a726f6c6f632d64 
00000001d0dfed10:  3b66663939623223  3a79616c70736964 
00000001d0dfed20:  743b656e696c6e69  67696c612d747865 
00000001d0dfed30:  7265746e65633a6e  0000000000000064 
00000001d0dfed40:  00000131e83b4458  0000000066d8f24d 
00000001d0dfed50:  7035207870323a67  6772616d3b302078 
00000001d0dfed60:  3a7466656c2d6e69  7265766f3b787038 
00000001d0dfed70:  6469683a776f6c66  00000000010103e7 
00000001d0dfed80: <757364622e206775  0000000066d8d2f0 
00000001d0dfed90:  726f6c6f637b7463  6f663b303030233a 
00000001d0dfeda0:  3a657a69732d746e  00000131e83b4300 
00000001d0dfedb0:  000000006d08bb79  00000131e83b4458 
00000001d0dfedc0:  000000006d08bb79  0000000000000260 
00000001d0dfedd0:  00000131edbdad80  00000131edba9480 
00000001d0dfede0:  0000000000000006  0000000066d8213c 
00000001d0dfedf0:  657269642d63702d  707b7069742d7463 
00000001d0dfee00:  3a6e6f697469736f  0000000066d81a3d 
00000001d0dfee10:  00000131edba5630  622e207400000004 
00000001d0dfee20:  00000131edbd5578  00000131e83b4300 
00000001d0dfee30:  00000131edba94f0  00000131edba94d0 
00000001d0dfee40:  00000131edba94c0  0000000000000240 
00000001d0dfee50:  00000131edbd4940  00000131edba94a0 
00000001d0dfee60:  0000000000000002  00000000010101c1 
00000001d0dfee70:  00000131e83b4300  00000000010107eb 

goroutine 1 [syscall]:
github.com/aarzilli/golua/lua._Cfunc_lua_pcall(0x131e83b4300, 0xffffffff00000000, 0x1, 0x0)
	_cgo_gotypes.go:1140 +0x54
github.com/aarzilli/golua/lua.(*State).pcall.func1(0xc000054050, 0x0, 0xffffffffffffffff, 0x1, 0x0)
	E:/fanou/golua/lua/golua_c_lua51.go:165 +0xab
github.com/aarzilli/golua/lua.(*State).pcall(0xc000054050, 0x0, 0xffffffffffffffff, 0x1, 0x0)
	E:/fanou/golua/lua/golua_c_lua51.go:165 +0x59
github.com/aarzilli/golua/lua.(*State).callEx(0xc000054050, 0x0, 0xffffffffffffffff, 0x131edb92201, 0x0, 0x0)
	E:/fanou/golua/lua/lua.go:222 +0x13a
github.com/aarzilli/golua/lua.(*State).Call(0xc000054050, 0x0, 0xffffffffffffffff, 0x0, 0x0)
	E:/fanou/golua/lua/lua.go:235 +0x53
github.com/aarzilli/golua/lua.(*State).DoFile(0xc000054050, 0x10666a6, 0x24, 0x0, 0x0)
	E:/fanou/golua/lua/lauxlib.go:99 +0x1ac
main.main()
	E:/fanou/golua/_example/quickstart.go:19 +0xab
rax     0x3ff0000000000000
rbx     0x66da4080
rcx     0x0
rdi     0x131e83b4300
rsi     0x131edbb0de0
rbp     0x1d0dfee90
rsp     0x1d0dfed80
r8      0x1
r9      0x131edbb0e00
r10     0x1
r11     0x131edbb0de0
r12     0x240
r13     0x131edbd4940
r14     0x131edba94a0
r15     0x2
rip     0x1010401
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by aarzilli** [comment]
Do you have a minimal example code that reproduces this issue.

**Comment by aarzilli** [comment]
Closing, no feedback.
