### ISSUE TITLE
compile fail with lua5.1.2

### ISSUE THREAD

**Issue by crayon-kid** [aarzilli/golua#107]
# github.com/aarzilli/golua/lua
C:\Users\lingsan\go\pkg\mod\github.com\aarzilli\golua@v0.0.0-20210507130708-11106aa57765\lua\golua_c_lua51.go:114:105: cannot use (func literal)() (type _Ctype_longlong) as type _Ctype_long in return argument

**Comment by aarzilli** [comment]
Can not reproduce, also there is no function literal at that line.
