### ISSUE TITLE
cannot run on windows

### ISSUE THREAD

**Issue by yg7001** [aarzilli/golua#25]
I 've compiled it on windows xp successfully, but when I run go test, error occured!

C:>go test github.com/aarzilli/golua/lua
unexpected fault address 0x4ac9d7
fatal error: fault
[signal 0xc0000005 code=0x1 addr=0x4ac9d7 pc=0x4ac9f5]

runtime stack:
invalid spdelta 339960 -1
runtime: unexpected return pc for x_cgo_thread_start called from 0x4ac9ed00
runtime.throw(0x61de3e)
        D:/GoDev/golang/src/pkg/runtime/panic.c:464 +0x67
runtime.sigpanic()
        D:/GoDev/golang/src/pkg/runtime/os_windows.c:340 +0xe1
invalid spdelta 339960 -1
runtime: unexpected return pc for x_cgo_thread_start called from 0x4ac9ed00
x_cgo_thread_start()
        ?:0 +0x1e

goroutine 1 [running]:
runtime.asmcgocall(0x4ac9d7, 0x2e2784)
        D:/GoDev/golang/src/pkg/runtime/asm_386.s:585 +0x22 fp=0x2e277c
newm(0x417470, 0x0)
        D:/GoDev/golang/src/pkg/runtime/proc.c:908 +0x8a fp=0x2e2798
runtime.main()
        D:/GoDev/golang/src/pkg/runtime/proc.c:191 +0x3a fp=0x2e27cc
runtime.goexit()
        D:/GoDev/golang/src/pkg/runtime/proc.c:1394 fp=0x2e27d0
FAIL    github.com/aarzilli/golua/lua   0.469s

**Comment by 54huige** [comment]
# github.com/aarzilli/golua/lua
_cgo_export.c:197:7: error: redefinition of 'golua_callgofunction'
 GoInt golua_callgofunction(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~~~~~~~~~
_cgo_export.c:24:7: note: previous definition of 'golua_callgofunction' was here
 GoInt golua_callgofunction(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~~~~~~~~~
_cgo_export.c:216:7: error: redefinition of 'golua_interface_newindex_callback'
 GoInt golua_interface_newindex_callback(GoUintptr p0, GoUint p1, char* p2)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:43:7: note: previous definition of 'golua_interface_newindex_callback' was here
 GoInt golua_interface_newindex_callback(GoUintptr p0, GoUint p1, char* p2)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:237:7: error: redefinition of 'golua_interface_index_callback'
 GoInt golua_interface_index_callback(GoUintptr p0, GoUint p1, char* p2)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:64:7: note: previous definition of 'golua_interface_index_callback' was here
 GoInt golua_interface_index_callback(GoUintptr p0, GoUint p1, char* p2)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:258:7: error: redefinition of 'golua_gchook'
 GoInt golua_gchook(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~
_cgo_export.c:85:7: note: previous definition of 'golua_gchook' was here
 GoInt golua_gchook(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~
_cgo_export.c:277:7: error: redefinition of 'golua_callpanicfunction'
 GoInt golua_callpanicfunction(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:104:7: note: previous definition of 'golua_callpanicfunction' was here
 GoInt golua_callpanicfunction(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:296:13: error: redefinition of 'golua_idtointerface'
 GoInterface golua_idtointerface(GoUint p0)
             ^~~~~~~~~~~~~~~~~~~
_cgo_export.c:123:13: note: previous definition of 'golua_idtointerface' was here
 GoInterface golua_idtointerface(GoUint p0)
             ^~~~~~~~~~~~~~~~~~~
_cgo_export.c:313:13: error: redefinition of 'golua_cfunctiontointerface'
 GoInterface golua_cfunctiontointerface(GoUintptr* p0)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:140:13: note: previous definition of 'golua_cfunctiontointerface' was here
 GoInterface golua_cfunctiontointerface(GoUintptr* p0)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:330:11: error: redefinition of 'golua_callallocf'
 GoUintptr golua_callallocf(GoUintptr p0, GoUintptr p1, GoUint p2, GoUint p3)
           ^~~~~~~~~~~~~~~~
_cgo_export.c:157:11: note: previous definition of 'golua_callallocf' was here
 GoUintptr golua_callallocf(GoUintptr p0, GoUintptr p1, GoUint p2, GoUint p3)
           ^~~~~~~~~~~~~~~~
_cgo_export.c:353:6: error: redefinition of 'go_panic_msghandler'
 void go_panic_msghandler(GoUintptr p0, char* p1)
      ^~~~~~~~~~~~~~~~~~~
_cgo_export.c:180:6: note: previous definition of 'go_panic_msghandler' was here
 void go_panic_msghandler(GoUintptr p0, char* p1)
