### ISSUE TITLE
undefined reference issue

### ISSUE THREAD

**Issue by sunshine8** [aarzilli/golua#31]
when i run go get -u -tags llua github.com/aarzilli/golua/lua,the result is the ld report many undefined reference.such as below:

/usr/local/lib/liblua.a(lvm.o): In function `Arith':
lvm.c:(.text+0x485): undefined reference to `pow'
lvm.c:(.text+0x4b4): undefined reference to `floor'
/usr/local/lib/liblua.a(lvm.o): In function `luaV_execute':
lvm.c:(.text+0x22c1): undefined reference to `floor'
lvm.c:(.text+0x23de): undefined reference to `pow'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_tan':
lmathlib.c:(.text+0x9f): undefined reference to `tan'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_tanh':
lmathlib.c:(.text+0xcf): undefined reference to `tanh'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_sqrt':
lmathlib.c:(.text+0x11c): undefined reference to `sqrt'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_sin':
lmathlib.c:(.text+0x13f): undefined reference to `sin'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_sinh':
lmathlib.c:(.text+0x16f): undefined reference to `sinh'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_floor':
lmathlib.c:(.text+0x29f): undefined reference to `floor'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_random':
lmathlib.c:(.text+0x3be): undefined reference to `floor'
lmathlib.c:(.text+0x406): undefined reference to `floor'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_pow':
lmathlib.c:(.text+0x48a): undefined reference to `pow'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_log':
lmathlib.c:(.text+0x50f): undefined reference to `log'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_log10':
lmathlib.c:(.text+0x53f): undefined reference to `log10'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_fmod':
lmathlib.c:(.text+0x666): undefined reference to `fmod'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_exp':
lmathlib.c:(.text+0x67f): undefined reference to `exp'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_cos':
lmathlib.c:(.text+0x6af): undefined reference to `cos'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_cosh':
lmathlib.c:(.text+0x6df): undefined reference to `cosh'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_ceil':
lmathlib.c:(.text+0x70f): undefined reference to `ceil'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_atan':
lmathlib.c:(.text+0x73f): undefined reference to `atan'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_atan2':
lmathlib.c:(.text+0x78a): undefined reference to `atan2'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_asin':
lmathlib.c:(.text+0x7bf): undefined reference to `asin'
/usr/local/lib/liblua.a(lmathlib.o): In function `math_acos':
lmathlib.c:(.text+0x7ef): undefined reference to `acos'
/usr/local/lib/liblua.a(loadlib.o): In function `ll_loadfunc':
loadlib.c:(.text+0x878): undefined reference to `dlsym'
loadlib.c:(.text+0x8d1): undefined reference to `dlopen'
loadlib.c:(.text+0x8e9): undefined reference to `dlerror'
loadlib.c:(.text+0x900): undefined reference to `dlerror'
/usr/local/lib/liblua.a(loadlib.o): In function `gctm':
loadlib.c:(.text+0xcbc): undefined reference to `dlclose'
/usr/local/lib/liblua.a(lcode.o): In function `codearith':
lcode.c:(.text+0x1118): undefined reference to `pow'
lcode.c:(.text+0x1140): undefined reference to `floor'
collect2: ld returned 1 exit status

what shoud i do?

**Comment by aarzilli** [comment]
Your problem sounds similar to [this problem](https://github.com/aarzilli/golua/issues/20)

**Comment by sunshine8** [comment]
@aarzilli I saw the "#cgo luaa LDFLAGS: -llua -lm -ldl" in the lua.go file.I think it did not work for me.My lua library's name is lua,not lua5.1

**Comment by sunshine8** [comment]
I use "go get -u -tags luaa github.com/aarzilli/golua/lua" and it works. Although I am not clear understand what happended.Any Suggestions?

**Comment by sunshine8** [comment]
@aarzilli I consult some document about cgo and build constraints.Whether the README.ME about install golua: "go get -u -tags llua github.com/aarzilli/golua/lua" is wrong? Is the -tags llua changes to -tags luaa ok?

**Comment by aarzilli** [comment]
Compiling lua from source results in a static library file (liblua.a) that needs different options for the linker.
Most people use the lua provided by their distribution and that's always a shared library.

**Comment by sunshine8** [comment]
@aarzilli Yeah,I compiled lua from source and got a static library file (liblua.a).I want to know is my solution is ok?

**Comment by aarzilli** [comment]
The command in the README will work for people who use liblua that comes with their distro.
