### ISSUE TITLE
PushGoFunction registers invalid type

### ISSUE THREAD

**Issue by admin36** [aarzilli/golua#36]
I'm attempting to build a module loader in go and push the loader function into the lua_state package.preload. as follows:

```go
func PreloadModule(LUA_STATE *lua.State, MOD_NAME string, LOADER_FUNC lua.LuaGoFunction) {
    LUA_STATE.GetField(lua.LUA_GLOBALSINDEX, "package")
    LUA_STATE.GetField(LUA_STATE.GetTop(), "preload")
    LUA_STATE.PushGoFunction(LOADER_FUNC)
    LUA_STATE.SetField(2, MOD_NAME)
}
```

```go
...
PreloadModule(L, "mymodule", func(L *lua.State) int {
    fmt.Println('Hello From Require')
    return 0
})
...
```

```lua
require('mymodule')
main.lua:1: module 'mymodule' not found:
```

It appears functions get pushed into the lua_state as type userdata, and lua fails to call the package.preload entry as it does not see it as a callable function.

C API notes that C functions get pushed as type function http://pgl.yoyo.org/luai/i/lua_pushcfunction can we mimic this behavior with lua.PushGoFunction ?

Thanks!

**Comment by aarzilli** [comment]
AFAIK no, go functions need a to be called by a trampoline and we can't dynamically create new C functions.

**Comment by admin36** [comment]
@aarzilli Thanks for your feedback. I took a little bit to tromp around the bindings and found that behavior was already implemented for method L.SetMetaMethod().

Please review the above fork/commit which includes a new helper function to push a LuaGoFunction closure to the stack. If you see no issues with the implimentation, I can submit a pull request.

My addition has resolved my module preloader issue. Thanks!

**Comment by aarzilli** [comment]
Make a pull request, I'll merge it. Thanks!
