### ISSUE TITLE
Support for Lua 5.3

### ISSUE THREAD

**Issue by Ambrevar** [aarzilli/golua#42]
Any plan?

**Comment by aarzilli** [comment]
I haven't looked into it.

**Comment by Ambrevar** [comment]
What is holding support back?

I found this fork: https://github.com/dnestorov/golua
Worth merging?

**Comment by aarzilli** [comment]
Last time I checked lua5.3 wasn't in ubuntu's repositories. I took a stab at this and published it as the lua5.3 branch, it seems to work.
