### ISSUE TITLE
Cannot build on CentOS 7

### ISSUE THREAD

**Issue by nikolay-turpitko** [aarzilli/golua#43]
Please notice that https://github.com/aarzilli/golua/blob/master/lua/lua.go#L9 cannot be build on CentOS 7.

The issue is with naming of lua*.pc file, which is used by pkg-config tool. Refer to https://code.google.com/p/grafx2/issues/detail?id=328 for similar discussion and some investigations. Not sure whether guys solved issue in their project, but I was not able to google any solution or another useful discussion on the topic either.

In the nutshell, different linux distros, have a habit to name this file differently:
- Debian / Ubuntu - lua5.1.pc
- Arch / CentOS / RedHat - lua.pc.

There is no build constraint for #cgo pseudo directive in Go comments to differentiate between linux distros.

Suggestion to pass "llua" tag in the closed #34 won't help, because execution won't reach line 11 where this tag checked as it fails at the line 9 where pkg-config invoked:

    # pkg-config --cflags lua5.1
    Package lua5.1 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `lua5.1.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'lua5.1' found
    pkg-config: exit status 1

Only workaround for me was to do: `sed -i -r -e "s/(#cgo .*)lua5.1(.*)/\1lua\2/" vendor/lua/lua.go` in my build script, which is rather brittle and lame solution.

Probably, it's better to remove `#cgo pkg-config` directive at all, as it is broken for lua and provide flags via env variables or tags only.

**Comment by nikolay-turpitko** [comment]
Another possible workaround is to add symlink besides passing tag "llua": `ln -s /usr/lib64/pkgconfig/lua.pc /usr/lib64/pkgconfig/lua5.1.pc`, which is also contradicts #cgo directives intent that "Package-specific flags should be set using the directives, not the environment variables, so that builds work in unmodified environments.", because it requires env modification more serious than setting env variable.

**Comment by aarzilli** [comment]
At some point this was fixed by linking directly to the relevant headers inside lua/lua/, I must have introduced this regression at some point.

**Comment by aarzilli** [comment]
Should be fixed now, if it isn't reopen the issue.

Thanks for reporting this.
