### ISSUE TITLE
golua have link error, running go 1.7.3

### ISSUE THREAD

**Issue by qingfengshuixu** [aarzilli/golua#50]
win64.env 
CGO_ENABLED=1

link error:
lib/../lib/libntdll.a(dudjbs01971.o):(.idata$5+0x0): multiple definition of `__imp_sqrt'
d:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/lib/../lib/libmsvcrt.a(dglbbs01052.o):(.idata$5+0x0): first defined here
d:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/lib/../lib/libntdll.a(dudjbs01968.o):(.idata$5+0x0): multiple definition of `__imp_sin'
d:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/lib/../lib/libmsvcrt.a(dglbbs01047.o):(.idata$5+0x0): first defined here
d:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/lib/../lib/libntdll.a(dudjbs01966.o):(.idata$5+0x0): multiple definition of `__imp_pow'
who have this question? how to solve this question?

**Comment by aarzilli** [comment]
See if reading this helps you: https://groups.google.com/forum/#!topic/golang-nuts/fW4KZQ05G_8

**Comment by huangwei1024** [comment]
same problem for me
```
x86_64-w64-mingw32/lib/../lib/libntdll.a(dgvcs01971.o):(.idata$5+0x0): multiple definition of `__imp_sqrt'
```

```
#cgo windows,!llua LDFLAGS: -L${SRCDIR} -llua -lmingwex -lmingw32
```
it can ok, when you put liblua.a(compiled with mingw64) under go-lua src
