### ISSUE TITLE
why hide pcall

### ISSUE THREAD

**Issue by huangwei1024** [aarzilli/golua#53]
```
void clua_hide_pcall(lua_State *L)
{
	lua_getglobal(L, "pcall");
	lua_setglobal(L, "unsafe_pcall");
	lua_pushnil(L);
	lua_setglobal(L, "pcall");

	lua_getglobal(L, "xpcall");
	lua_setglobal(L, "unsafe_xpcall");
	lua_pushnil(L);
	lua_setglobal(L, "xpcall");
}
```

why `pcall` and `xpcall` is unsafe ?

**Comment by aarzilli** [comment]
liblua likes to setjmp/longjmp, cgo doesn't want that.

**Comment by huangwei1024** [comment]
> They are only safe to be called from Lua code that never calls back to Go. 

`pcall(f)` are safely when then function `f` and its subfunctions only invoke Lua code, no any communicate with go, its right?

**Comment by aarzilli** [comment]
yes.
