### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by viphxin** [aarzilli/golua#54]
version: go1.8.1
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/aarzilli/golua/lua.newState.func1(0x5518030, 0x4b692a0, 0xc424492300)
	/Users/xxx/workspace/src/xxx/src/github.com/aarzilli/golua/lua/lua.go:39 +0xb7
github.com/aarzilli/golua/lua.newState(0x5518030, 0xc400000002)
	/Users/xxx/workspace/src/xxx/src/github.com/aarzilli/golua/lua/lua.go:40 +0x168
github.com/aarzilli/golua/lua.NewState(0x0)
	/Users/xxx/workspace/src/xxx/src/github.com/aarzilli/golua/lua/lauxlib.go:168 +0x2f
github.com/stevedonovan/luar.Init(0xc428333d00)

**Comment by viphxin** [comment]
how to solve this question?ths

**Comment by aarzilli** [comment]
I'm not getting this error, are you sure you have the latest version of golua? What's the output of
```
git rev-parse HEAD
```
?

What operating system are you using?

**Comment by viphxin** [comment]
my os is macOS Sierra, go version is 1.8.1. and i overwrite golua with the newest version yesterday. But got the error below:
# github.com/aarzilli/golua/lua
could not determine kind of name for C.lua_tointeger
could not determine kind of name for C.lua_tonumber

git rev-parse HEAD display:
398439a45a7a3ed2b25143f1e7dfd1ca8c413af8

**Comment by aarzilli** [comment]
You are using the wrong branch, you need lua5.2 if you have lua5.2.
