### ISSUE TITLE
using the library from a vendor directory

### ISSUE THREAD

**Issue by ggeorgiev** [aarzilli/golua#57]
Hi,

When I try to use this from a vendor directory I get: 

vendor/github.com/aarzilli/golua/lua/golua.go:6:17: fatal error: lua.h: No such file or directory
 #include <lua.h>
                 ^
compilation terminated.

What I am doing wrong?

Thanks

**Comment by aarzilli** [comment]
Some vendor tool like to strip files they don't think they are used. Is `github.com/aarzilli/golua/lua/lua/lua.h` in your vendor directory? If it isn't complain to your vendor vendor.

**Comment by ggeorgiev** [comment]
This is the case. Thank you for pointing this out. I am trying to find an option to resolve this using govendor - a very popular and commonly used tool and I can't find.

I think the reason it to strip the directory is that there is no golang file in it. Is it possible for you to add a dummy.go file in there to workaround the issue.

**Comment by aarzilli** [comment]
`govendor fetch github.com/aarzilli/golua/lua/lua` doesn't work?

**Comment by ggeorgiev** [comment]
govendor v1.0.8 - sync, fetch, get - nothing works

**Comment by aarzilli** [comment]
@kardianos: what's the canonical solution to make govendor happy with a directory that only contains code for the C compiler?

**Comment by kardianos** [comment]
Add the tree, denoted with "hat" ^

**Comment by ggeorgiev** [comment]
@kardianos Sorry for the dumb question. Add it where?

**Comment by kardianos** [comment]
Search readme for ^ or tree.

**Comment by ggeorgiev** [comment]
Thanks.
