### ISSUE TITLE
re-allocation bug

### ISSUE THREAD

**Issue by glycerine** [aarzilli/golua#64]
Thanks for golua. Generally it is fantastic.

I hit the following bug, causing a firey crash in my program.

https://github.com/aarzilli/golua/blob/master/lua/lua.go#L80
~~~
newSlice := make([]interface{}, index, cap(L.registry)*2)
~~~
should read
~~~
newSlice := make([]interface{}, index, (1+cap(L.registry))*2)
~~~
because when cap is 0, the slice doesn't grow. Since 2 * 0 is still 0.

**Comment by aarzilli** [comment]
How did the cap(L.registry) become zero when it's initialized to 8?

**Comment by glycerine** [comment]
> How did the cap(L.registry) become zero when it's initialized to 8?

Ah hah! Mystery solved. My attempt at ToThread allocates a *State, but was defaulting in the registry, so cap 0, in https://github.com/aarzilli/golua/issues/65
~~~
// lua_tothread
func (L *State) ToThread(index int) *State {
    s := &State{s: (*C.lua_State)(unsafe.Pointer(C.lua_tothread(L.s, C.int(index))))}
    registerGoState(s)
    return s
}
~~~
