### ISSUE TITLE
process is terminated when there is a lua error

### ISSUE THREAD

**Issue by 0chunhui** [aarzilli/golua#67]
Can I modify the function "callEx" in lua.go to remove C.GOLUA_DEFAULT_MSGHANDLER?
like this:
...
//L.GetGlobal(C.GOLUA_DEFAULT_MSHANDLER)
//erridex := L.GetTop() - nargs - 1
//L.Insert(erridx)
r := L.pcall(nargs, nresults, 0)
//L.Remove(erridx)
...

If I don't use any error handling function in "pcall", would there be any problem?
I tried, seems OK without terminated. But I don't understand.

**Comment by aarzilli** [comment]
If you remove that any lua error will terminate your program.

**Comment by 0chunhui** [comment]
Can you tell me the reason, please?
I remove the error handler. When there is a lua error, my program is no terminated and just print the last line of the lua error.

**Comment by 0chunhui** [comment]
In my program, I create many lua_State. If one of thems encounter a lua error， I just close it, but the others can still run.

**Comment by tianhongye** [comment]
I also hate this design，  I hope to export xcall pcall ,  provide a lower level api，
not packaged
