### ISSUE TITLE
How about add method to get *C.lua_State?

### ISSUE THREAD

**Issue by edolphin-ydf** [aarzilli/golua#75]
Thanks for your work on golua.
After look around the source, i found that there is no way to get the `*C.lua_State`.
Is it possible to export the member `L.s` for some special usage? 
Eg: in order to void call from go to c many times, i'v writen some c api which accept `lua_State*` as a parameter( and some other params), but there is no way that i can access the `L.s` except modify the golua source code.

**Comment by aarzilli** [comment]
If you submit a PR for this I will approve it.

**Comment by edolphin-ydf** [comment]
PR created. And because of i'm using lua5.3, it's on lua5.3 branch.
