### ISSUE TITLE
Unable to build on CentOS 7

### ISSUE THREAD

**Issue by nwidger** [aarzilli/golua#81]
I know a similar issue related to building on CentOS 7 was fixed in #43, but I think this may be a new issue.  On CentOS 7, installing the `lua` package gets you a `/usr/lib64/liblua-5.1.so`, as seen listed under the "Files" section [here](https://centos.pkgs.org/7/centos-x86_64/lua-5.1.4-15.el7.x86_64.rpm.html).  But as far as I can tell, [lua.go](https://github.com/aarzilli/golua/blob/master/lua/lua.go) provides no way to link to Lua via `-llua-5.1` on Linux.  Is this a known issue, or perhaps I'm doing something wrong?  If not, perhaps this is a possible workaround?

``` diff
#cgo CFLAGS: -I ${SRCDIR}/lua
#cgo llua LDFLAGS: -llua
#cgo luaa LDFLAGS: -llua -lm -ldl
+ #cgo lluadash5.1 LDFLAGS: -llua-5.1
#cgo luajit LDFLAGS: -lluajit-5.1
- #cgo linux,!llua,!luaa,!luajit LDFLAGS: -llua5.1
+ #cgo linux,!llua,!luaa,!lluadash5.1,!luajit LDFLAGS: -llua5.1
#cgo darwin,!luaa,!luajit pkg-config: lua5.1
#cgo freebsd,!luaa,!luajit LDFLAGS: -llua-5.1
#cgo windows,!llua,!luajit LDFLAGS: -L${SRCDIR} -llua -lmingwex -lmingw32
```

The horrible `luadash5.1` tag name was chosen since hyphens [are apparently not allowed in build tags](https://golang.org/pkg/go/build/#hdr-Build_Constraints).

**Comment by aarzilli** [comment]
Let me know if this doesn't work.

**Comment by nwidger** [comment]
@aarzilli That worked perfectly, thanks so much!
