### ISSUE TITLE
Safe execution of Lua Code

### ISSUE THREAD

**Issue by antony-jr** [aarzilli/golua#83]
Is there a way to only allow execution of harmless code like calculation and calling go function and impair the ability to require modules like os if we set os variable to nil via golang.

**EDIT**:

Only way I can think of is setting ```os = nil``` with DoString and using regex to strip all ```require``` calls.

**Comment by aarzilli** [comment]
This library is just a thin wrapper for the standard C implementation of lua. Any sandboxing methods applicable to normal lua in C should be applicable to this library.

**Comment by antony-jr** [comment]
@aarzilli Okay then I will be using docker to run unsafe code.
