### ISSUE TITLE
Which branch to choose if I use Lua 5.3

### ISSUE THREAD

**Issue by davix** [aarzilli/golua#86]
Hi, my project is using Lua 5.3.
Should I choose `lua5.3` branch, or `master` branch with "-tags lua53"?
Which branch will have latest bug fixing and more stable?

Thanks!

**Comment by aarzilli** [comment]
You should use the build tag (-tags lua53). Although at this point they are the same.

**Comment by davix** [comment]
Thanks @aarzilli for the reply!
