### ISSUE TITLE
build error on windows

### ISSUE THREAD

**Issue by 54huige** [aarzilli/golua#88]
# github.com/aarzilli/golua/lua
_cgo_export.c:197:7: error: redefinition of 'golua_callgofunction'
 GoInt golua_callgofunction(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~~~~~~~~~
_cgo_export.c:24:7: note: previous definition of 'golua_callgofunction' was here
 GoInt golua_callgofunction(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~~~~~~~~~
_cgo_export.c:216:7: error: redefinition of 'golua_interface_newindex_callback'
 GoInt golua_interface_newindex_callback(GoUintptr p0, GoUint p1, char* p2)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:43:7: note: previous definition of 'golua_interface_newindex_callback' was here
 GoInt golua_interface_newindex_callback(GoUintptr p0, GoUint p1, char* p2)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:237:7: error: redefinition of 'golua_interface_index_callback'
 GoInt golua_interface_index_callback(GoUintptr p0, GoUint p1, char* p2)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:64:7: note: previous definition of 'golua_interface_index_callback' was here
 GoInt golua_interface_index_callback(GoUintptr p0, GoUint p1, char* p2)
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:258:7: error: redefinition of 'golua_gchook'
 GoInt golua_gchook(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~
_cgo_export.c:85:7: note: previous definition of 'golua_gchook' was here
 GoInt golua_gchook(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~
_cgo_export.c:277:7: error: redefinition of 'golua_callpanicfunction'
 GoInt golua_callpanicfunction(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:104:7: note: previous definition of 'golua_callpanicfunction' was here
 GoInt golua_callpanicfunction(GoUintptr p0, GoUint p1)
       ^~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:296:13: error: redefinition of 'golua_idtointerface'
 GoInterface golua_idtointerface(GoUint p0)
             ^~~~~~~~~~~~~~~~~~~
_cgo_export.c:123:13: note: previous definition of 'golua_idtointerface' was here
 GoInterface golua_idtointerface(GoUint p0)
             ^~~~~~~~~~~~~~~~~~~
_cgo_export.c:313:13: error: redefinition of 'golua_cfunctiontointerface'
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:140:13: note: previous definition of 'golua_cfunctiontointerface' was here
 GoInterface golua_cfunctiontointerface(GoUintptr* p0)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
_cgo_export.c:330:11: error: redefinition of 'golua_callallocf'
 GoUintptr golua_callallocf(GoUintptr p0, GoUintptr p1, GoUint p2, GoUint p3)
           ^~~~~~~~~~~~~~~~
_cgo_export.c:157:11: note: previous definition of 'golua_callallocf' was here
 GoUintptr golua_callallocf(GoUintptr p0, GoUintptr p1, GoUint p2, GoUint p3)
           ^~~~~~~~~~~~~~~~
_cgo_export.c:353:6: error: redefinition of 'go_panic_msghandler'
 void go_panic_msghandler(GoUintptr p0, char* p1)
      ^~~~~~~~~~~~~~~~~~~
_cgo_export.c:180:6: note: previous definition of 'go_panic_msghandler' was here
 void go_panic_msghandler(GoUintptr p0, char* p1)

**Comment by aarzilli** [comment]
There's no reason that I can see that this would happen, I suggest maybe starting from a fresh checkout of the repository.
