### ISSUE TITLE
/usr/bin/ld: cannot find -llua5.4 collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by lx-world** [aarzilli/golua#93]
/usr/bin/ld: cannot find -llua5.4
collect2: error: ld returned 1 exit status

**Comment by lx-world** [comment]
wsl：  go build -tags lua54

**Comment by lx-world** [comment]
go build -tags llua

# github.com/aarzilli/golua/lua
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_luaL_loadfile':
/tmp/go-build/cgo-gcc-prolog:66: undefined reference to `luaL_loadfile'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_equal':
/tmp/go-build/cgo-gcc-prolog:87: undefined reference to `lua_equal'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_lessthan':
/tmp/go-build/cgo-gcc-prolog:157: undefined reference to `lua_lessthan'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_objlen':
/tmp/go-build/cgo-gcc-prolog:177: undefined reference to `lua_objlen'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_pcall':
/tmp/go-build/cgo-gcc-prolog:200: undefined reference to `lua_pcall'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_setfenv':
/tmp/go-build/cgo-gcc-prolog:298: undefined reference to `lua_setfenv'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_tointeger':
/tmp/go-build/cgo-gcc-prolog:333: undefined reference to `lua_tointeger'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_tonumber':
/tmp/go-build/cgo-gcc-prolog:353: undefined reference to `lua_tonumber'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_yield':
/tmp/go-build/cgo-gcc-prolog:374: undefined reference to `lua_yield'
/usr/bin/ld: $WORK/b002/_x003.o: in function `clua_openio':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/golua_c_lua51.go:56: undefined reference to `lua_call'
/usr/bin/ld: $WORK/b002/_x003.o: in function `clua_openmath':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/golua_c_lua51.go:63: undefined reference to `lua_call'
/usr/bin/ld: $WORK/b002/_x003.o: in function `clua_openpackage':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/golua_c_lua51.go:70: undefined reference to `lua_call'
/usr/bin/ld: $WORK/b002/_x003.o: in function `clua_openstring':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/golua_c_lua51.go:77: undefined reference to `lua_call'
/usr/bin/ld: $WORK/b002/_x003.o: in function `clua_opentable':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/golua_c_lua51.go:84: undefined reference to `lua_call'
/usr/bin/ld: $WORK/b002/_x003.o:/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/golua_c_lua51.go:91: more undefined references to `lua_call' follow
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_getfenv':
/tmp/go-build/cgo-gcc-prolog:125: undefined reference to `lua_getfenv'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_insert':
/tmp/go-build/cgo-gcc-prolog:139: undefined reference to `lua_insert'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_remove':
/tmp/go-build/cgo-gcc-prolog:245: undefined reference to `lua_remove'
/usr/bin/ld: $WORK/b002/_x003.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_replace':
/tmp/go-build/cgo-gcc-prolog:259: undefined reference to `lua_replace'
/usr/bin/ld: $WORK/b002/_x005.o: in function `_cgo_96dc7cf2f219_Cfunc_lua_newuserdata':
/tmp/go-build/cgo-gcc-prolog:610: undefined reference to `lua_newuserdata'
/usr/bin/ld: $WORK/b002/_x007.o: in function `callback_function':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/c-golua.c:78: undefined reference to `lua_remove'
/usr/bin/ld: $WORK/b002/_x007.o: in function `callback_panicf':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/c-golua.c:275: undefined reference to `lua_tointeger'
/usr/bin/ld: $WORK/b002/_x007.o: in function `clua_pushgofunction':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/c-golua.c:107: undefined reference to `lua_newuserdata'
/usr/bin/ld: $WORK/b002/_x007.o: in function `clua_pushgostruct':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/c-golua.c:127: undefined reference to `lua_newuserdata'
/usr/bin/ld: $WORK/b002/_x007.o: in function `clua_atpanic':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/c-golua.c:290: undefined reference to `lua_tointeger'
/usr/bin/ld: $WORK/b002/_x007.o: in function `clua_openbase':
/home/lx/go/pkg/mod/github.com/aarzilli/golua@v0.0.0-20201227100147-717e9930eb2d/lua/c-golua.c:338: undefined reference to `lua_call'
/usr/bin/ld: /usr/local/lib/liblua.a(lobject.o): in function `numarith':
lobject.c:(.text+0x251): undefined reference to `pow'
/usr/bin/ld: /usr/local/lib/liblua.a(lvm.o): in function `luaV_modf':
lvm.c:(.text+0x13ff): undefined reference to `fmod'
/usr/bin/ld: /usr/local/lib/liblua.a(lvm.o): in function `luaV_execute':
lvm.c:(.text+0x473d): undefined reference to `pow'
/usr/bin/ld: lvm.c:(.text+0x4922): undefined reference to `pow'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_log10':
lmathlib.c:(.text+0x123): undefined reference to `log10'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_pow':
lmathlib.c:(.text+0x238): undefined reference to `pow'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_tanh':
lmathlib.c:(.text+0x263): undefined reference to `tanh'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_sinh':
lmathlib.c:(.text+0x293): undefined reference to `sinh'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_cosh':
lmathlib.c:(.text+0x2c3): undefined reference to `cosh'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_tan':
lmathlib.c:(.text+0x2f3): undefined reference to `tan'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_sqrt':
lmathlib.c:(.text+0x356): undefined reference to `sqrt'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_sin':
lmathlib.c:(.text+0x383): undefined reference to `sin'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_log':
lmathlib.c:(.text+0x519): undefined reference to `log10'
/usr/bin/ld: lmathlib.c:(.text+0x526): undefined reference to `log'
/usr/bin/ld: lmathlib.c:(.text+0x548): undefined reference to `log2'
/usr/bin/ld: lmathlib.c:(.text+0x55c): undefined reference to `log'
/usr/bin/ld: lmathlib.c:(.text+0x570): undefined reference to `log'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_exp':
lmathlib.c:(.text+0x5f3): undefined reference to `exp'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_cos':
lmathlib.c:(.text+0x623): undefined reference to `cos'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_atan':
lmathlib.c:(.text+0x680): undefined reference to `atan2'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_asin':
lmathlib.c:(.text+0x6b3): undefined reference to `asin'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_acos':
lmathlib.c:(.text+0x6e3): undefined reference to `acos'
/usr/bin/ld: /usr/local/lib/liblua.a(lmathlib.o): in function `math_fmod':
lmathlib.c:(.text+0xe33): undefined reference to `fmod'
/usr/bin/ld: /usr/local/lib/liblua.a(loadlib.o): in function `lookforfunc':
loadlib.c:(.text+0x525): undefined reference to `dlsym'
/usr/bin/ld: loadlib.c:(.text+0x586): undefined reference to `dlopen'
/usr/bin/ld: loadlib.c:(.text+0x609): undefined reference to `dlerror'
/usr/bin/ld: loadlib.c:(.text+0x631): undefined reference to `dlerror'
/usr/bin/ld: /usr/local/lib/liblua.a(loadlib.o): in function `gctm':
loadlib.c:(.text+0x731): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

**Comment by aarzilli** [comment]
In your first error the linker can not find a library, your second error also looks like some configuration problem with your build environment. In either cases it's a problem I can not help you with.
