### ISSUE TITLE
 Why use unsafe_pcall/unsafe_xpcall instead of  pcall/xpcall

### ISSUE THREAD

**Issue by lx-world** [aarzilli/golua#95]
Why use unsafe_pcall/unsafe_xpcall instead of  pcall/xpcall

**Comment by lx-world** [comment]
` They are only safe to be called from Lua code that never calls back to Go` , 
 why?

**Comment by aarzilli** [comment]
Because:

> Lua's exceptions are incompatible with Go, golua works around this incompatibility by setting up protected execution environments in lua.State.DoString, lua.State.DoFile and lua.State.Call and turning every exception into a Go panic.

**Comment by lx-world** [comment]
> Because:
> 
> > Lua's exceptions are incompatible with Go, golua works around this incompatibility by setting up protected execution environments in lua.State.DoString, lua.State.DoFile and lua.State.Call and turning every exception into a Go panic.

Thank you very much

**Comment by lx-world** [comment]
A third-party library is called in Lua, such as protoc.lua. If pcall is used in this library, golua will report an error and cannot find pcall. How to solve this?

**Comment by lx-world** [comment]
example:
`pcall=unsafe_pcall`


Will there be any problems or risks in such use?

**Comment by aarzilli** [comment]
> Will there be any problems or risks in such use?

No.

**Comment by lx-world** [comment]
Does that mean that I cannot call any third-party libraries with pcall and xpcall?

**Comment by aarzilli** [comment]
> Does that mean that I cannot call any third-party libraries with pcall and xpcall?

You can but only if there is never any Go frame on the stack between the point where an error is raised and the point where pcall is used.

> If the third-party library used uses pcall/xpcall, the program will not start. Is there a solution for this?

Comment out the code that hides pcall, xpcall?

**Comment by lx-world** [comment]
> > Does that mean that I cannot call any third-party libraries with pcall and xpcall?
> 
> You can but only if there is never any Go frame on the stack between the point where an error is raised and the point where pcall is used.
> 
> > If the third-party library used uses pcall/xpcall, the program will not start. Is there a solution for this?
> 
> Comment out the code that hides pcall, xpcall?


Is there any risk in commenting out pcall/xpcall?

**Comment by aarzilli** [comment]
>  Is there any risk in commenting out pcall/xpcall?

Do you mean commenting out the code that hides pcall and xpcall? Yes, all the lua code will have to be audited to make sure that it doesn't use errors + pcall/xpcall in a way that can crash the go runtime.
